name: publish-index

on:
  push:
    paths:
      - "book/home.ipynb"
      - ".github/workflows/publish_index.yml"
    branches:
      - main
      - feature/homepage
      - maintentance/homepage

permissions:
  contents: write

jobs:
  publish-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the books
        run: |
          jupyter-book build ./book/home.ipynb

      - name: GitHub Pages publish Index
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/_page/home/html
          destination_dir: ./
          keep_files: true
