name: publish-book

on:
  push:
    paths:
      - "book/**"
      - ".github/workflows"
    branches:
      - main

permissions:
  contents: write

jobs:
  publish-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the books
        run: |
          jupyter-book build ./book/plutocracy_report.ipynb
          jupyter-book build ./book/extensive_analysis.ipynb

      - name: GitHub Pages publish Report
        uses: peaceiris/actions-gh-pages@v3.9.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/_build/_page/plutocracy_report/html
          destination_dir: ./report/

      # - name: GitHub Pages publish Extensive Analysis
      #   uses: peaceiris/actions-gh-pages@v3.6.1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./book/_build/_page/extensive_analysis/html
      #     keep_files: true
